# Generated by Django 3.0 on 2020-05-10 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asper', '0002_userdetail_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
