# Generated by Django 3.0 on 2020-05-11 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asper', '0004_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='phone',
        ),
    ]
