# Generated by Django 3.0 on 2020-05-11 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asper', '0006_userdetail_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='phone',
            field=models.TextField(max_length=10, null=True),
        ),
    ]
