# Generated by Django 3.0 on 2020-05-11 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asper', '0007_auto_20200511_2115'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
