# Generated by Django 3.0 on 2020-05-13 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asper', '0010_userdetail_hobbies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='hobbies',
        ),
    ]
