# Generated by Django 3.0 on 2020-05-13 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asper', '0011_remove_userdetail_hobbies'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='dept',
            field=models.TextField(max_length=20, null=True),
        ),
    ]
