# Generated by Django 3.0 on 2020-05-14 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asper', '0014_designassignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designassignment',
            name='AssigmentImg',
        ),
    ]
