# Generated by Django 3.0 on 2020-05-14 22:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asper', '0015_remove_designassignment_assigmentimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignSubmit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Assignmentimng', models.FileField(null=True, upload_to='')),
                ('Status', models.BooleanField(null=True)),
                ('usr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
