# Generated by Django 3.0 on 2020-05-15 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asper', '0017_appassignment_appsubmit_webassignment_websubmit'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsubmit',
            name='AssigmentNo',
            field=models.TextField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='designsubmit',
            name='AssigmentNo',
            field=models.TextField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='websubmit',
            name='AssigmentNo',
            field=models.TextField(max_length=5, null=True),
        ),
    ]
