# Generated by Django 3.0 on 2020-05-15 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asper', '0018_auto_20200515_1828'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssiNo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Assino', models.IntegerField(max_length=5, null=True)),
                ('usr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='designsubmit',
            name='AssigmentNo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='asper.AssiNo'),
        ),
    ]
