# Generated by Django 3.0 on 2020-05-15 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asper', '0019_auto_20200515_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designassignment',
            name='AssigmentNo',
            field=models.IntegerField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='designsubmit',
            name='AssigmentNo',
            field=models.IntegerField(max_length=5, null=True),
        ),
        migrations.DeleteModel(
            name='AssiNo',
        ),
    ]
