# Generated by Django 3.0 on 2020-05-15 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asper', '0020_auto_20200515_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designassignment',
            name='AssigmentNo',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='designsubmit',
            name='AssigmentNo',
            field=models.IntegerField(null=True),
        ),
    ]
