# Generated by Django 3.0 on 2020-05-15 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asper', '0021_auto_20200515_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designsubmit',
            name='AssigmentNo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='asper.DesignAssignment'),
        ),
    ]
