# Generated by Django 3.0 on 2020-05-15 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asper', '0022_auto_20200515_2002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='designsubmit',
            old_name='AssigmentNo',
            new_name='AssignNo',
        ),
        migrations.AlterField(
            model_name='designassignment',
            name='AssigmentNo',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
