# Generated by Django 3.0 on 2020-05-17 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asper', '0023_auto_20200515_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='EmailA',
            field=models.TextField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='FirstN',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='LastN',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
