# Generated by Django 3.0 on 2020-05-17 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asper', '0024_auto_20200517_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='firsttask',
            name='ud',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='asper.UserDetail'),
        ),
    ]
