# Generated by Django 3.0 on 2020-05-17 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asper', '0029_userskills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appsubmit',
            name='AssigmentNo',
        ),
        migrations.RemoveField(
            model_name='websubmit',
            name='AssigmentNo',
        ),
        migrations.AddField(
            model_name='appsubmit',
            name='AssignNo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='asper.DesignAssignment'),
        ),
        migrations.AddField(
            model_name='websubmit',
            name='AssignNo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='asper.DesignAssignment'),
        ),
    ]
