# Generated by Django 3.0 on 2020-05-18 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asper', '0032_userport'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='JoinDate',
            field=models.DateField(null=True),
        ),
    ]
