# Generated by Django 3.0 on 2020-05-18 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asper', '0033_userdetail_joindate'),
    ]

    operations = [
        migrations.AddField(
            model_name='firsttask',
            name='FirstTS',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='ProjectPosted',
            field=models.DateField(null=True),
        ),
    ]
