# Generated by Django 3.0 on 2020-05-26 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asper', '0034_auto_20200518_0957'),
    ]

    operations = [
        migrations.CreateModel(
            name='Round0',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.TextField(max_length=20, null=True)),
                ('LastName', models.TextField(max_length=20, null=True)),
                ('EmailAdd', models.TextField(max_length=30, null=True)),
            ],
        ),
    ]
