# Generated by Django 3.0 on 2020-06-23 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asper', '0039_firsttask_usr'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Round0',
        ),
    ]
